### ISSUE TITLE
Voltera V-One Multipurpose PCB Printer

### ISSUE THREAD

**Issue by reeeeeee-dev** [theprimelab/roadmap#5]
## Suggestion
Acquire a Voltera V-One

## Purpose
Mainly, this would be used for printing/preparing PCBs for various electronics projects.
This specific model not only prints PCBs but also drills, places, and solders in one machine.
Also Bentonville West High School has one and we don't.

## Sources
https://www.voltera.io/store/v-one

**Comment by Dizeeee** [comment]
This has been something we've been looking in to, and this model seems like a very good fit for the lab. While it's not 100% certain that we get one, this is one of the higher priority items I want to take care of.

**Comment by jackmalcom** [comment]
After talking to Dr. Nelson, it seems like offering to purchase PCBs for students from a fab like OSH Park would be a better idea. It would cut down on costs and give us more flexibility.
